CREATE USER "j2ee-jira" WITH NOCREATEDB NOCREATEROLE;
ALTER USER "j2ee-jira" WITH ENCRYPTED PASSWORD 'GW52Atvflwh6zM';
CREATE USER "j2ee-confluence" WITH NOCREATEDB;
ALTER USER "j2ee-confluence" WITH ENCRYPTED PASSWORD 'zqIbhrEzcoFI23';
CREATE USER "j2ee-bitbucket" WITH NOCREATEDB;
ALTER USER "j2ee-bitbucket" WITH ENCRYPTED PASSWORD 'HFZiYrqkZaKK5B';

CREATE DATABASE "j2ee-jira" ENCODING 'UNICODE' LC_COLLATE 'C' LC_CTYPE 'C' TEMPLATE template0;
GRANT ALL PRIVILEGES ON DATABASE "j2ee-jira" TO "j2ee-jira";

CREATE DATABASE "j2ee-confluence" ENCODING 'UNICODE';
GRANT ALL PRIVILEGES ON DATABASE "j2ee-confluence" TO "j2ee-confluence";

CREATE DATABASE "j2ee-bitbucket" ENCODING 'UNICODE';
GRANT ALL PRIVILEGES ON DATABASE "j2ee-bitbucket" TO "j2ee-bitbucket";
